from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass(frozen=True)
class PopIIILWBackgroundHistory:
    """Tabulated external LW background in dimensionless ``J21`` units."""

    redshift: np.ndarray
    j21: np.ndarray
    source_path: Path

    def interpolate(self, z_obs: np.ndarray | float) -> np.ndarray | float:
        """Interpolate ``J21(z)`` without extrapolating beyond the source table."""

        redshift = np.asarray(z_obs, dtype=float)
        if not np.all(np.isfinite(redshift)):
            raise ValueError("z_obs must be finite")
        if np.any(redshift < self.redshift[0]) or np.any(redshift > self.redshift[-1]):
            raise ValueError(
                "z_obs lies outside the external LW history range "
                f"[{self.redshift[0]}, {self.redshift[-1]}]"
            )
        interpolated = np.interp(redshift, self.redshift, self.j21)
        if np.ndim(z_obs) == 0:
            return float(interpolated)
        return np.asarray(interpolated, dtype=float)


def load_popiii_lw_background_history(
    path: str | Path,
    *,
    redshift_column: str = "redshift",
    j21_column: str = "j21_lw_total",
) -> PopIIILWBackgroundHistory:
    """Load a validated external LW history from a CSV table.

    The Zeus21 bridge product generated by
    ``scripts/analysis/reproduce_zeus21_popiii.py`` uses the default column
    names.  Other external models can be attached by naming their explicit
    redshift and dimensionless ``J21`` columns.
    """

    source_path = Path(path).expanduser().resolve()
    if not source_path.is_file():
        raise FileNotFoundError(f"Pop III LW history is missing: {source_path}")

    with source_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"Pop III LW history has no CSV header: {source_path}")
        missing = {redshift_column, j21_column}.difference(reader.fieldnames)
        if missing:
            raise ValueError(
                f"Pop III LW history is missing required columns {sorted(missing)}: {source_path}"
            )
        rows = list(reader)

    if len(rows) < 2:
        raise ValueError("Pop III LW history must contain at least two rows")
    try:
        redshift = np.asarray([float(row[redshift_column]) for row in rows], dtype=float)
        j21 = np.asarray([float(row[j21_column]) for row in rows], dtype=float)
    except (TypeError, ValueError) as exc:
        raise ValueError("Pop III LW history columns must contain numeric values") from exc

    if not np.all(np.isfinite(redshift)) or np.any(redshift < 0.0):
        raise ValueError("Pop III LW history redshifts must be finite and non-negative")
    if not np.all(np.isfinite(j21)) or np.any(j21 < 0.0):
        raise ValueError("Pop III LW history J21 values must be finite and non-negative")

    order = np.argsort(redshift)
    redshift = redshift[order]
    j21 = j21[order]
    if np.any(np.diff(redshift) <= 0.0):
        raise ValueError("Pop III LW history redshifts must be unique")
    return PopIIILWBackgroundHistory(
        redshift=redshift,
        j21=j21,
        source_path=source_path,
    )


__all__ = ["PopIIILWBackgroundHistory", "load_popiii_lw_background_history"]
